# Generated by Django 4.2.11 on 2024-04-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adres',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='user',
            name='telnmbr',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True, verbose_name='Телефон'),
        ),
    ]
