# Generated by Django 4.2.11 on 2024-04-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='unit',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Единица измерения'),
        ),
    ]
