# Generated by Django 4.2.11 on 2024-04-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='img_for_order',
            field=models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='cart',
            name='select_buy',
            field=models.BooleanField(default=True, verbose_name='Выделено к оплате'),
        ),
    ]
