# Generated by Django 4.2.11 on 2024-04-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='chck_buy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Изображение'),
        ),
    ]
