# Generated by Django 4.2.11 on 2024-04-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cart_img_for_order_cart_select_buy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='img_for_order',
            field=models.ImageField(blank=True, height_field=40, null=True, storage='goods_images', upload_to='', verbose_name='Изображение'),
        ),
    ]
