# Generated by Django 4.2.11 on 2024-04-06 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cart_chck_buy_cart_image'),
        ('carts', '0004_alter_cart_img_for_order'),
    ]

    operations = [
    ]
