# Generated by Django 4.2.11 on 2024-04-06 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_merge_20240406_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='chck_buy',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='image',
        ),
    ]
