# Generated by Django 4.2.11 on 2024-04-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_remove_cart_chck_buy_remove_cart_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='img_for_order',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='unit',
        ),
        migrations.AlterField(
            model_name='cart',
            name='select_buy',
            field=models.BooleanField(default=True, verbose_name='VX'),
        ),
    ]
