# Generated by Django 4.2.11 on 2024-07-26 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_remove_cart_img_for_order_remove_cart_unit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('id',), 'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзина'},
        ),
    ]
