# Generated by Django 4.2.11 on 2024-08-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_alter_cart_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Количество'),
        ),
    ]
