# Generated by Django 4.2.11 on 2024-04-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_products_options_alter_products_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cats_images', verbose_name='Изображение'),
        ),
    ]
