# Generated by Django 4.2.11 on 2024-07-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_products_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='count_for_mid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Цена мелкого опта от единиц'),
        ),
        migrations.AddField(
            model_name='products',
            name='price_low',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Цена опт'),
        ),
        migrations.AddField(
            model_name='products',
            name='price_mid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Цена мелкий опт'),
        ),
    ]
