# Generated by Django 4.2.11 on 2024-07-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_products_count_for_low_alter_products_count_for_mid'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='count_for',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7, verbose_name='Единиц товара'),
        ),
    ]
