# Generated by Django 4.2.11 on 2024-08-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_products_created_time_stamp_products_discount_low_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='products',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='products',
            name='is_residual',
            field=models.BooleanField(default=False, verbose_name='В остатках'),
        ),
        migrations.AddField(
            model_name='products',
            name='residual_1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Остаток'),
        ),
        migrations.AddField(
            model_name='products',
            name='residual_2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Остаток'),
        ),
        migrations.AddField(
            model_name='products',
            name='residual_3',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Остаток'),
        ),
        migrations.AddField(
            model_name='products',
            name='residual_4',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Остаток'),
        ),
    ]
