# Generated by Django 4.2.11 on 2024-08-02 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_products_residual_5_products_residual_6_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='residual_1',
        ),
        migrations.RemoveField(
            model_name='products',
            name='residual_2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='residual_3',
        ),
        migrations.RemoveField(
            model_name='products',
            name='residual_4',
        ),
        migrations.RemoveField(
            model_name='products',
            name='residual_5',
        ),
        migrations.RemoveField(
            model_name='products',
            name='residual_6',
        ),
        migrations.AddField(
            model_name='products',
            name='residual',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Остатки (вносить через ПРОБЕЛ)'),
        ),
    ]
