# Generated by Django 4.2.11 on 2024-08-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_remove_products_residual_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Количество'),
        ),
    ]
