# Generated by Django 4.2.11 on 2024-08-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0014_alter_products_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='count_for',
            field=models.IntegerField(default=1, verbose_name='Единиц товара'),
        ),
        migrations.AlterField(
            model_name='products',
            name='count_for_low',
            field=models.IntegerField(default=1, verbose_name='Единиц товара для опта'),
        ),
        migrations.AlterField(
            model_name='products',
            name='count_for_mid',
            field=models.IntegerField(default=1, verbose_name='Единиц товара для мелкого опта'),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='products',
            name='residual',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Остатки (ЦЕЛЫЕ, вносить через ПРОБЕЛ)'),
        ),
    ]
