# Generated by Django 4.2.11 on 2024-09-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0015_alter_products_count_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='count_for',
            field=models.IntegerField(default=1, verbose_name='Минимум единиц товара'),
        ),
    ]
