# Generated by Django 4.2.11 on 2024-04-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11, verbose_name='Стоимость'),
        ),
    ]
