# Generated by Django 4.2.11 on 2024-04-06 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total_cost',
        ),
    ]
