# Generated by Django 4.2.11 on 2024-08-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ожидает оплаты', 'Ожидает оплаты'), ('В обработке', 'В обработке'), ('Собран', 'Собран'), ('В пути', 'В пути'), ('Доставлено', 'Доставлено')], default='Ожидает оплаты', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
