# Generated by Django 4.2.11 on 2024-09-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_order_is_paid_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ожидает оплаты', 'Ожидает оплаты'), ('В обработке', 'В обработке'), ('Собран', 'Собран'), ('В пути', 'В пути'), ('Доставлено', 'Доставлено')], default='Ожидает оплаты', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
