# Generated by Django 4.2.11 on 2024-09-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='link',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Ссылка на оплату'),
        ),
    ]
