# Generated by Django 4.2.11 on 2024-10-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='link',
            field=models.URLField(blank=True, max_length=350, null=True, verbose_name='Ссылка на оплату'),
        ),
    ]
